# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mac/Documents/c++/render_engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mac/Documents/c++/render_engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mac/Documents/c++/render_engine/CMakeFiles /Users/mac/Documents/c++/render_engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mac/Documents/c++/render_engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named render_engine

# Build rule for target.
render_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 render_engine
.PHONY : render_engine

# fast build rule for target.
render_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/build
.PHONY : render_engine/fast

src/framebuffer.o: src/framebuffer.cpp.o
.PHONY : src/framebuffer.o

# target to build an object file
src/framebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/framebuffer.cpp.o
.PHONY : src/framebuffer.cpp.o

src/framebuffer.i: src/framebuffer.cpp.i
.PHONY : src/framebuffer.i

# target to preprocess a source file
src/framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/framebuffer.cpp.i
.PHONY : src/framebuffer.cpp.i

src/framebuffer.s: src/framebuffer.cpp.s
.PHONY : src/framebuffer.s

# target to generate assembly for a file
src/framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/framebuffer.cpp.s
.PHONY : src/framebuffer.cpp.s

src/genmath.o: src/genmath.cpp.o
.PHONY : src/genmath.o

# target to build an object file
src/genmath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/genmath.cpp.o
.PHONY : src/genmath.cpp.o

src/genmath.i: src/genmath.cpp.i
.PHONY : src/genmath.i

# target to preprocess a source file
src/genmath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/genmath.cpp.i
.PHONY : src/genmath.cpp.i

src/genmath.s: src/genmath.cpp.s
.PHONY : src/genmath.s

# target to generate assembly for a file
src/genmath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/genmath.cpp.s
.PHONY : src/genmath.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/matrix22.o: src/matrix22.cpp.o
.PHONY : src/matrix22.o

# target to build an object file
src/matrix22.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/matrix22.cpp.o
.PHONY : src/matrix22.cpp.o

src/matrix22.i: src/matrix22.cpp.i
.PHONY : src/matrix22.i

# target to preprocess a source file
src/matrix22.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/matrix22.cpp.i
.PHONY : src/matrix22.cpp.i

src/matrix22.s: src/matrix22.cpp.s
.PHONY : src/matrix22.s

# target to generate assembly for a file
src/matrix22.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/matrix22.cpp.s
.PHONY : src/matrix22.cpp.s

src/matrix33.o: src/matrix33.cpp.o
.PHONY : src/matrix33.o

# target to build an object file
src/matrix33.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/matrix33.cpp.o
.PHONY : src/matrix33.cpp.o

src/matrix33.i: src/matrix33.cpp.i
.PHONY : src/matrix33.i

# target to preprocess a source file
src/matrix33.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/matrix33.cpp.i
.PHONY : src/matrix33.cpp.i

src/matrix33.s: src/matrix33.cpp.s
.PHONY : src/matrix33.s

# target to generate assembly for a file
src/matrix33.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/matrix33.cpp.s
.PHONY : src/matrix33.cpp.s

src/matrix44.o: src/matrix44.cpp.o
.PHONY : src/matrix44.o

# target to build an object file
src/matrix44.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/matrix44.cpp.o
.PHONY : src/matrix44.cpp.o

src/matrix44.i: src/matrix44.cpp.i
.PHONY : src/matrix44.i

# target to preprocess a source file
src/matrix44.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/matrix44.cpp.i
.PHONY : src/matrix44.cpp.i

src/matrix44.s: src/matrix44.cpp.s
.PHONY : src/matrix44.s

# target to generate assembly for a file
src/matrix44.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/matrix44.cpp.s
.PHONY : src/matrix44.cpp.s

src/quaternion.o: src/quaternion.cpp.o
.PHONY : src/quaternion.o

# target to build an object file
src/quaternion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/quaternion.cpp.o
.PHONY : src/quaternion.cpp.o

src/quaternion.i: src/quaternion.cpp.i
.PHONY : src/quaternion.i

# target to preprocess a source file
src/quaternion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/quaternion.cpp.i
.PHONY : src/quaternion.cpp.i

src/quaternion.s: src/quaternion.cpp.s
.PHONY : src/quaternion.s

# target to generate assembly for a file
src/quaternion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/quaternion.cpp.s
.PHONY : src/quaternion.cpp.s

src/rasterizer.o: src/rasterizer.cpp.o
.PHONY : src/rasterizer.o

# target to build an object file
src/rasterizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/rasterizer.cpp.o
.PHONY : src/rasterizer.cpp.o

src/rasterizer.i: src/rasterizer.cpp.i
.PHONY : src/rasterizer.i

# target to preprocess a source file
src/rasterizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/rasterizer.cpp.i
.PHONY : src/rasterizer.cpp.i

src/rasterizer.s: src/rasterizer.cpp.s
.PHONY : src/rasterizer.s

# target to generate assembly for a file
src/rasterizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/rasterizer.cpp.s
.PHONY : src/rasterizer.cpp.s

src/vector2.o: src/vector2.cpp.o
.PHONY : src/vector2.o

# target to build an object file
src/vector2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/vector2.cpp.o
.PHONY : src/vector2.cpp.o

src/vector2.i: src/vector2.cpp.i
.PHONY : src/vector2.i

# target to preprocess a source file
src/vector2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/vector2.cpp.i
.PHONY : src/vector2.cpp.i

src/vector2.s: src/vector2.cpp.s
.PHONY : src/vector2.s

# target to generate assembly for a file
src/vector2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/vector2.cpp.s
.PHONY : src/vector2.cpp.s

src/vector3.o: src/vector3.cpp.o
.PHONY : src/vector3.o

# target to build an object file
src/vector3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/vector3.cpp.o
.PHONY : src/vector3.cpp.o

src/vector3.i: src/vector3.cpp.i
.PHONY : src/vector3.i

# target to preprocess a source file
src/vector3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/vector3.cpp.i
.PHONY : src/vector3.cpp.i

src/vector3.s: src/vector3.cpp.s
.PHONY : src/vector3.s

# target to generate assembly for a file
src/vector3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/vector3.cpp.s
.PHONY : src/vector3.cpp.s

src/vector4.o: src/vector4.cpp.o
.PHONY : src/vector4.o

# target to build an object file
src/vector4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/vector4.cpp.o
.PHONY : src/vector4.cpp.o

src/vector4.i: src/vector4.cpp.i
.PHONY : src/vector4.i

# target to preprocess a source file
src/vector4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/vector4.cpp.i
.PHONY : src/vector4.cpp.i

src/vector4.s: src/vector4.cpp.s
.PHONY : src/vector4.s

# target to generate assembly for a file
src/vector4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_engine.dir/build.make CMakeFiles/render_engine.dir/src/vector4.cpp.s
.PHONY : src/vector4.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... render_engine"
	@echo "... src/framebuffer.o"
	@echo "... src/framebuffer.i"
	@echo "... src/framebuffer.s"
	@echo "... src/genmath.o"
	@echo "... src/genmath.i"
	@echo "... src/genmath.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrix22.o"
	@echo "... src/matrix22.i"
	@echo "... src/matrix22.s"
	@echo "... src/matrix33.o"
	@echo "... src/matrix33.i"
	@echo "... src/matrix33.s"
	@echo "... src/matrix44.o"
	@echo "... src/matrix44.i"
	@echo "... src/matrix44.s"
	@echo "... src/quaternion.o"
	@echo "... src/quaternion.i"
	@echo "... src/quaternion.s"
	@echo "... src/rasterizer.o"
	@echo "... src/rasterizer.i"
	@echo "... src/rasterizer.s"
	@echo "... src/vector2.o"
	@echo "... src/vector2.i"
	@echo "... src/vector2.s"
	@echo "... src/vector3.o"
	@echo "... src/vector3.i"
	@echo "... src/vector3.s"
	@echo "... src/vector4.o"
	@echo "... src/vector4.i"
	@echo "... src/vector4.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

